/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkflowGuideRouteImport } from './routes/workflow-guide'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntityCreateRouteImport } from './routes/entity.create'
import { Route as EntityEntityIdRouteImport } from './routes/entity.$entityId'
import { Route as EntityEditEntityIdRouteImport } from './routes/entity.edit.$entityId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowGuideRoute = WorkflowGuideRouteImport.update({
  id: '/workflow-guide',
  path: '/workflow-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityCreateRoute = EntityCreateRouteImport.update({
  id: '/entity/create',
  path: '/entity/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityEntityIdRoute = EntityEntityIdRouteImport.update({
  id: '/entity/$entityId',
  path: '/entity/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityEditEntityIdRoute = EntityEditEntityIdRouteImport.update({
  id: '/entity/edit/$entityId',
  path: '/entity/edit/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/templates': typeof TemplatesRoute
  '/workflow-guide': typeof WorkflowGuideRoute
  '/workflows': typeof WorkflowsRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
  '/entity/edit/$entityId': typeof EntityEditEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/templates': typeof TemplatesRoute
  '/workflow-guide': typeof WorkflowGuideRoute
  '/workflows': typeof WorkflowsRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
  '/entity/edit/$entityId': typeof EntityEditEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/templates': typeof TemplatesRoute
  '/workflow-guide': typeof WorkflowGuideRoute
  '/workflows': typeof WorkflowsRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
  '/entity/edit/$entityId': typeof EntityEditEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/templates'
    | '/workflow-guide'
    | '/workflows'
    | '/entity/$entityId'
    | '/entity/create'
    | '/entity/edit/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/templates'
    | '/workflow-guide'
    | '/workflows'
    | '/entity/$entityId'
    | '/entity/create'
    | '/entity/edit/$entityId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/templates'
    | '/workflow-guide'
    | '/workflows'
    | '/entity/$entityId'
    | '/entity/create'
    | '/entity/edit/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TemplatesRoute: typeof TemplatesRoute
  WorkflowGuideRoute: typeof WorkflowGuideRoute
  WorkflowsRoute: typeof WorkflowsRoute
  EntityEntityIdRoute: typeof EntityEntityIdRoute
  EntityCreateRoute: typeof EntityCreateRoute
  EntityEditEntityIdRoute: typeof EntityEditEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-guide': {
      id: '/workflow-guide'
      path: '/workflow-guide'
      fullPath: '/workflow-guide'
      preLoaderRoute: typeof WorkflowGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/create': {
      id: '/entity/create'
      path: '/entity/create'
      fullPath: '/entity/create'
      preLoaderRoute: typeof EntityCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$entityId': {
      id: '/entity/$entityId'
      path: '/entity/$entityId'
      fullPath: '/entity/$entityId'
      preLoaderRoute: typeof EntityEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/edit/$entityId': {
      id: '/entity/edit/$entityId'
      path: '/entity/edit/$entityId'
      fullPath: '/entity/edit/$entityId'
      preLoaderRoute: typeof EntityEditEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TemplatesRoute: TemplatesRoute,
  WorkflowGuideRoute: WorkflowGuideRoute,
  WorkflowsRoute: WorkflowsRoute,
  EntityEntityIdRoute: EntityEntityIdRoute,
  EntityCreateRoute: EntityCreateRoute,
  EntityEditEntityIdRoute: EntityEditEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
