/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntityCreateRouteImport } from './routes/entity.create'
import { Route as EntityEntityIdRouteImport } from './routes/entity.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityCreateRoute = EntityCreateRouteImport.update({
  id: '/entity/create',
  path: '/entity/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityEntityIdRoute = EntityEntityIdRouteImport.update({
  id: '/entity/$entityId',
  path: '/entity/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entity/$entityId' | '/entity/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entity/$entityId' | '/entity/create'
  id: '__root__' | '/' | '/entity/$entityId' | '/entity/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntityEntityIdRoute: typeof EntityEntityIdRoute
  EntityCreateRoute: typeof EntityCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/create': {
      id: '/entity/create'
      path: '/entity/create'
      fullPath: '/entity/create'
      preLoaderRoute: typeof EntityCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$entityId': {
      id: '/entity/$entityId'
      path: '/entity/$entityId'
      fullPath: '/entity/$entityId'
      preLoaderRoute: typeof EntityEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntityEntityIdRoute: EntityEntityIdRoute,
  EntityCreateRoute: EntityCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
