/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntityCreateRouteImport } from './routes/entity.create'
import { Route as EntityEntityIdRouteImport } from './routes/entity.$entityId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as EntityEditEntityIdRouteImport } from './routes/entity.edit.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityCreateRoute = EntityCreateRouteImport.update({
  id: '/entity/create',
  path: '/entity/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityEntityIdRoute = EntityEntityIdRouteImport.update({
  id: '/entity/$entityId',
  path: '/entity/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityEditEntityIdRoute = EntityEditEntityIdRouteImport.update({
  id: '/entity/edit/$entityId',
  path: '/entity/edit/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
  '/entity/edit/$entityId': typeof EntityEditEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
  '/entity/edit/$entityId': typeof EntityEditEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/entity/$entityId': typeof EntityEntityIdRoute
  '/entity/create': typeof EntityCreateRoute
  '/entity/edit/$entityId': typeof EntityEditEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/entity/$entityId'
    | '/entity/create'
    | '/entity/edit/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/entity/$entityId'
    | '/entity/create'
    | '/entity/edit/$entityId'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/entity/$entityId'
    | '/entity/create'
    | '/entity/edit/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EntityEntityIdRoute: typeof EntityEntityIdRoute
  EntityCreateRoute: typeof EntityCreateRoute
  EntityEditEntityIdRoute: typeof EntityEditEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/create': {
      id: '/entity/create'
      path: '/entity/create'
      fullPath: '/entity/create'
      preLoaderRoute: typeof EntityCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$entityId': {
      id: '/entity/$entityId'
      path: '/entity/$entityId'
      fullPath: '/entity/$entityId'
      preLoaderRoute: typeof EntityEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/edit/$entityId': {
      id: '/entity/edit/$entityId'
      path: '/entity/edit/$entityId'
      fullPath: '/entity/edit/$entityId'
      preLoaderRoute: typeof EntityEditEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EntityEntityIdRoute: EntityEntityIdRoute,
  EntityCreateRoute: EntityCreateRoute,
  EntityEditEntityIdRoute: EntityEditEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
